import type React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ezalia24 - About Us",
    description: "Generated by create next app",
};

function page() {
  return (
    <div>About Page</div>
  )
}

export default page