import type React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ezalia24 - Contact Us",
    description: "Generated by create next app",
};


function page() {
  return (
    <div>Contact Page</div>
  )
}

export default page